nodes:
  # Wazuh indexer nodes
  indexer:
    - name: node-1
      ip: 172.31.24.165
   

  # Wazuh server nodes
  # If there is more than one Wazuh server
  # node, each one must have a node_type
  server:
    - name: wazuh-1
      ip: 172.31.24.165
   
  # Wazuh dashboard nodes
  dashboard:
    - name: dashboard
      ip: 172.31.24.165
